dictdb/urls.py
from django.conf.urls import include, url

from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('vocab.urls')),
]

vocab/urls.py
from django.conf.urls import url

from . import views

app_name = 'vocab'
urlpatterns = [
    url(r'^$', views.Index, name='index'),
    url(r'^viewall/', views.Viewall.as_view(), name='viewall'),
    url(r'^search/', views.Search, name='search'),
    url(r'^detail/(?P<search_text>[\w-]+)/$', views.Detail, name='detail'),
    url(r'^add/', views.add, name='add'),
    url(r'^backup_page/$', views.backup_page, name='backup_page'),   
    url(r'^import/$', views.restoreCSV, name='restoreCSV'),
  
    url(r'^searasdfch/', views.historylink, name='historylink'), 

]

vocab/models.py
from django.db import models
from django.utils import timezone
import datetime
class Word(models.Model):
    word_text = models.CharField(max_length=100)

    def __str__(self):
        return self.word_text

class Mean(models.Model):
    word = models.ForeignKey(Word, on_delete=models.CASCADE)
    mean_text = models.CharField(max_length=200)
    type_text = models.CharField(default='Unknown',max_length=20)
    sample = models.CharField(default='None',max_length=200)
    def __str__(self):
        return self.mean_text


class Search_History(models.Model):
    search_text= models.CharField(max_length=200)
    lasted_used= models.DateTimeField('date published')
    count = models.IntegerField(default=1)
    
    def __str__(self):
        return self.search_text

vocab/views.py
from django.shortcuts import render,render_to_response
from django.views import generic
from .models import Word, Mean, Search_History
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
import time
import datetime
import csv
import os
from django.contrib import messages
from django.core.files.storage import default_storage
import xml.etree.cElementTree as ET
from xml.etree.ElementTree import ElementTree
from django.utils import timezone
from django.shortcuts import render,get_object_or_404


def Index(request):
    search_list = Search_History.objects.order_by('-lasted_used')
    return render(request,'vocab/index.html',{'search_list' : search_list })

class Viewall(generic.ListView):
    template_name = 'vocab/viewall.html'
    context_object_name = 'word_list'
    def get_queryset(self):
        return Word.objects.order_by('word_text')

def Detail(request,search_text):
    word = Word.objects.filter(word_text__startswith=str(search_text))
    return render_to_response('vocab/detail.html', {'wordlist' : word})

def Search(request):
    search_text = request.POST.get('search_text', None)
    if Search_History.objects.filter(search_text=search_text):
        search_use = get_object_or_404(Search_History,search_text=search_text)
        search_use.lasted_used=timezone.now()
        search_use.count+=1
        search_use.save()
    else:
        search_use  = Search_History(search_text=search_text,lasted_used= timezone.now() )
        search_use.save()

    wordlist = Word.objects.filter(word_text__startswith=str(search_text)).order_by('word_text')
    
    return render_to_response('vocab/search.html', {'wordlist' : wordlist , 'search_text' :search_text} )

def historylink(request):
    searchtext= search.search_text
    wordlist = Word.objects.filter(word_text__startswith=str(searchtext)).order_by('word_text')
    
    return render_to_response('vocab/search.html', {'wordlist' : wordlist , 'search_text' :searchtext} )



def add(request):
    error_message = '' 
    if request.method == 'POST':
        word_text_form = request.POST['word']
        meaning_text_form = request.POST['meaning']
        meaning_type_text_form = request.POST['meaning_type']
        sample_sentence_text_form = request.POST['sample_sentence']

        if word_text_form !='' and meaning_text_form != '' and meaning_type_text_form != '' and sample_sentence_text_form != '': 
            if Word.objects.filter(word_text=word_text_form):  # check objects same name
                word = Word.objects.get(word_text=word_text_form)
                if not word.mean_set.filter(mean_text=meaning_text_form):  # check same mean
                    word.mean_set.create(mean_text=meaning_text_form,type_text=meaning_type_text_form,sample=sample_sentence_text_form) #Create new meaning
                    backupCSV(request)# Update to csv
                    backupXML(request)# Update to XML
                    error_message = 'Update Word Complete'
                else:
                    error_message = 'This meaning already in this word'

            else:  # not same name can create new word
                word = Word(word_text=word_text_form)
                word.save()
                word.mean_set.create(mean_text=meaning_text_form,type_text=meaning_type_text_form,sample=sample_sentence_text_form)
                error_message = 'Update Word Complete'
                backupCSV(request) # Update to csv
                backupXML(request)# Update to XML
        else:
            print('fill not complete')
            error_message = 'fill not complete'

  
    context = {'error_message':error_message}
    return render(request,'vocab/add.html',context)



def backup_page(request):
    backupXML(request)
    backupCSV(request)
    return render(request,'vocab/backup.html')


def backupCSV(request):
    all_word=Word.objects.all()
    cols = ['word','mean','type','sample']
    print(time.localtime())
    output = csv.DictWriter(open('vocab/backup/CSV_'+datetime.datetime.now().strftime("%d:%m:%y[%H:%M]")+'.csv','wt'), fieldnames=cols)
    output.writeheader()
    for word in all_word:
        output.writerow({'word':word.word_text})
        for mean in word.mean_set.all():
            output.writerow({'word': '',  'mean':mean.mean_text,'type': mean.type_text,'sample': mean.sample})

def restoreCSV(request):
    dirPath = 'vocab/backup/'
    if request.FILES != {}:  # Check file isn't empty
        csvFile = request.FILES['Backup_File']
        saveFilePath = default_storage.save(dirPath,csvFile)
        os.rename(saveFilePath,'{}{}'.format(dirPath,csvFile.name))
        all_word = Word.objects.all()
        for word in all_word:
            word.delete()  # clear old word
        with open('{}{}'.format(dirPath,csvFile.name)) as csvfile:        #with csvfile:

            reader = csv.DictReader(csvfile)
            for row in reader:
                if row['word'] != '':
                    if Word.objects.filter(word_text=row['word']):
                        word = Word.objects.get(word_text=row['word'])
                    else:
                        word = Word(word_text=row['word'])
                        word.save()
                else:
                    if not word.mean_set.filter(mean_text=row['mean']):  # if not have same meaning , create new meaning
                        word.mean_set.create(mean_text=row['mean'], type_text=row['type'], sample=row['sample'])

        return HttpResponseRedirect(reverse('vocab:viewall'))


def backupXML(request):
    all_word = Word.objects.all()
    root = ET.Element("vocab")
    for each_word in all_word:
        word = ET.SubElement(root,"word",name=each_word.word_text)
        for each_mean in each_word.mean_set.all():
            mean = ET.SubElement(word, "mean",name=each_mean.mean_text)
            ET.SubElement(mean, "type_text").text = each_mean.type_text
            ET.SubElement(mean, "sample").text = each_mean.sample

    tree = ET.ElementTree(root)
    tree.write('vocab/backup/XML_'+datetime.datetime.now().strftime("%d:%m:%y[%H:%M]")+'.xml')

def restoreXML(request):
    dirPath = 'vocab/backup/'
    if request.FILES != {}:  # Check file isn't empty
        xmlFile = request.FILES['Backup_File']
        saveFilePath = default_storage.save(dirPath,xmlFile)
        os.rename(saveFilePath,'{}{}'.format(dirPath,xmlFile.name))
        all_word = Word.objects.all()
        for word in all_word:
            word.delete()  # clear old word
        tree = ElementTree()
        tree.parse('{}{}'.format(dirPath,xmlFile.name))
        root = tree.getroot()
        for word in root:
            print(word.tag)
            if Word.objects.filter(word_text=word.name):
                 word = Word.objects.get(word_text=word.name)
            else:
                 word = Word(word_text=word.name)
                 word.save()
            for mean in word:
                if not word.mean_set.filter(mean_text=mean.get('name')):  # if not have same meaning , create new meaning
                    word.mean_set.create(mean_text=mean.get('name'), type_text=mean.find('type_text').text, sample=mean.find('sample').text)

        return HttpResponseRedirect(reverse('vocab:viewall'))    
        
        

vocab/templates/vocab/add.html
<!DOCTYPE html>

<head>

    <title>Add Word Page</title>
    {% load staticfiles %}
   
</head>
<body>
<h1>Add Your Word</h1>
<Form action="{% url 'vocab:add' %}" method="post">
    {% csrf_token %}
Word :<br>
<input type='text' name='word' size='40' autofocus><br><br>
  type : <select name="meaning_type">
    <option value="noun">noun</option>
    <option value="verb">verb</option>
    <option value="adverb">adverb</option>
    <option value="adjective">adjective</option>
    <option value="preprosition">preposition</option>
  </select><br><br>
Meaning :<br><input type='text' name='meaning' size='40'>
<h2>Sample Sentence :</h2>
<input type='text' name='sample_sentence'  size="40"><br><br>

<input type='submit' value='Submit'></form><br>

{% if error_message %}
    <b>{{error_message}}</b>
{%endif%}
<br><br>
<a href="../">Back Page</a>
</body>
</html>

vocab/templates/vocab/backup.html
{% load staticfiles %}

<form action="{% url 'vocab:restoreCSV' %}" method="post" enctype="multipart/form-data">
{% csrf_token %}
Select Backup CSV File:<input type="file" name="Backup_File" id="Backup_File">
<input type="submit"  value="Import" name="submit">
</form>
<action="{%url 'vocab:index' %}" style="display: inline;">
<input type="submit" value="Back"></form>

vocab/templates/vocab/detail.html
{% load staticfiles %}


{% if wordlist %}
{% for word in wordlist %}
<font size="10"><b>{{word.word_text}}</b></font><br><br>
<table border="1"> <tr>
<th>Mean</th><th>Example</th>
</tr>
<tr>
       {% for mean in word.mean_set.all %}
   <td>{{ mean.mean_text }} [{{ mean.type_text }}]</td> 
   <td>{{ mean.sample }}</td>
</tr>
{%endfor%}
{%endfor%}
</tr>
{% endif %}



</tr>
<table border="0"><tr><td>
<form action="{%url 'vocab:index' %}" style="display: inline;">
<input type="submit" value="Back"></form></td></tr>

vocab/templates/vocab/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Word Page</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'word_bank/style.css' %}" />
</head>
<body>
<h1>Add Your Word</h1>
<Form action="{% url 'vocab:add' %}" method="post">
    {% csrf_token %}
<br>
<input type='text' name='word' size='40' autofocus><br><br>
    {% for mean in word.mean %}
  <input type='text' name="mean{{ forloop.counter0 }}" value={{mean.mean_text}} size='40'>
  
   <select name="meaning_type">
   {% for type in type_list %}
       <option value="{{type}}"
       {% if type == mean.type_text %}selected="selected"{% endif %}>
       {{mean.type_text}}
       </option> {% endfor %} </select><br>
  <h2>Sample Sentence :</h2>
  <input type='text' name='sample_sentence' value={{mean.sample}} size="40"><br><br>
{% endfor %}



{% if error_message %}
    <b>{{error_message}}</b>
{%endif%}
<br><br>
<a href="../">Back Page</a>
</body>
</html>

vocab/templates/vocab/index.html
{% load staticfiles %}

    <script src="{% static 'rst2slides/javascript/angular.min.js' %}"></script>
    <script src="{% static 'rst2slides/javascript/jquery-1.12.3.min.js' %}"></script>
<table border="0.5">
<form action="{% url 'vocab:search' %}" method="post" style="display: inline;">
{% csrf_token %}
 <tr>
<th><input type="text" name="search_text"></th>

<th><input type="submit" value="Search"></th>

</form>
<th><form action="{% url 'vocab:viewall' %}" style="display: inline;">
<input type="submit" value="All Vocab"></form></th>

<th><form action="{% url 'vocab:backup_page' %}" style="display: inline;">
<input type="submit" value="Restore"></form></th>
 </tr>
<table border="2">
<tr>
<th>Search</th> <th>Date</th> <th>Used</th> 
</tr>
{% if search_list %}
{% for search in search_list %}
<tr>
  <td>{{search.search_text}}</td> 

<td>
{{ search.lasted_used }} </td><td>{{ search.count}}  </td> 
{% endfor %}</tr>
 {% endif %}
</tr>

vocab/templates/vocab/search.html
{% load staticfiles %}

{% if search_text == "" %}
<b>Your Search input is Empty Please Try again.</b>
{% else %}
<font size="4">Search result for <b>"{{ search_text }}"</b></font><br><br>
<table border="1">
  <tr>
<th>Word</th><th>Mean</th>
  </tr>
{% if wordlist %}
{% for word in wordlist %}
 <tr>
   <td><a href="{% url 'vocab:detail' word%}">{{word.word_text}}</td>
<td>
      {% for mean in word.mean_set.all %}
   {{ mean.mean_text }} [{{ mean.type_text }}]  
 {% endfor %}</td></tr>
</tr>
{%endfor%}
{% endif %}
{% endif %}<table border="0"><tr><td>
<th><form action="{%url 'vocab:index' %}" style="display: inline;">
<input type="submit" value="Back"></form></th></td></tr>

vocab/templates/vocab/viewall.html
{% load staticfiles %}
{% if word_list %}
    <table border="1">
     <tr>
     <th>Word</th>
     <th>Mean</th>
     </tr>
    {% for word in word_list %}
      <tr><td>      
<a href="{% url 'vocab:detail' word%}"> {{ word.word_text }}</a>
</td><td>
      {% for mean in word.mean_set.all %}
   {{ mean.mean_text }} [{{ mean.type_text }}]    <br>
 {% endfor %}</td></tr>
    
{% endfor %}
</table>
    
{% else %}
    <p>No polls are available.</p>
{% endif %}
<FORM><INPUT Type="button" VALUE="Back" onClick="history.go(-1);return true;"></FORM>